# Generated by Django 5.1.4 on 2026-01-01 16:18

import apps.trainings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('objective', models.TextField(blank=True, help_text='O que o colaborador aprenderá com este treinamento', verbose_name='Objetivo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.trainings.models.training_cover_path, verbose_name='Imagem de Capa')),
                ('reward_points', models.PositiveIntegerField(default=100, help_text='Pontos ganhos ao completar o treinamento', verbose_name='Pontos de Recompensa')),
                ('reward_badge', models.CharField(blank=True, help_text='Nome do badge conquistado', max_length=100, verbose_name='Badge/Medalha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Treinamento obrigatório para todos os colaboradores', verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Disponível a partir de')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name='Disponível até')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['order', 'title'],
                'unique_together': {('company', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('video_file', models.FileField(help_text='Formatos aceitos: MP4, WebM, MOV', upload_to=apps.trainings.models.video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='Arquivo de Vídeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='trainings/thumbnails/', verbose_name='Thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duração do vídeo em segundos', verbose_name='Duração (segundos)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='trainings.training', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['training', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserTrainingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Pontos Ganhos')),
                ('badge_earned', models.CharField(blank=True, max_length=100, verbose_name='Badge Conquistado')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conquistado em')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='trainings.training', verbose_name='Treinamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recompensa de Treinamento',
                'verbose_name_plural': 'Recompensas de Treinamentos',
                'unique_together': {('user', 'training')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Segundos Assistidos')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Posição em segundos onde o usuário parou', verbose_name='Última Posição')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='Vezes Assistido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='trainings.video', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Progresso de Usuário',
                'verbose_name_plural': 'Progressos de Usuários',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
