# Generated by Django 5.1.4 on 2026-01-02 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Selecione os colaboradores que devem ter acesso a este treinamento. Deixe vazio para tornar global (todos os colaboradores da empresa).', related_name='assigned_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Atribuídos'),
        ),
    ]
