# Generated by Django 5.1.4 on 2026-01-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_training_assigned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Texto da Pergunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500, verbose_name='Texto da Opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Resposta Correta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='trainings.question', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Nota mínima (0-100) para aprovação no quiz', verbose_name='Nota Mínima para Aprovação')),
                ('allow_multiple_attempts', models.BooleanField(default=True, help_text='Permite que o colaborador refaça o quiz caso não seja aprovado', verbose_name='Permitir Múltiplas Tentativas')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='trainings.training', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['training', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trainings.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0, help_text='Nota de 0 a 100', verbose_name='Nota')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total de Perguntas')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Respostas Corretas')),
                ('answers', models.JSONField(default=dict, help_text='Dicionário com question_id: choice_id das respostas', verbose_name='Respostas')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Concluído em')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='trainings.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quizzes',
                'ordering': ['-completed_at'],
            },
        ),
    ]
