# Generated by Django 5.1.4 on 2026-01-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning_type', models.CharField(choices=[('oral', 'Advertência Oral'), ('escrita', 'Advertência Escrita'), ('suspensao', 'Suspensão')], default='oral', max_length=20, verbose_name='Tipo de Advertência')),
                ('reason', models.TextField(help_text='Descrição detalhada do motivo da advertência', verbose_name='Motivo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='core.company', verbose_name='Empresa')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings_issued', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_received', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Advertência',
                'verbose_name_plural': 'Advertências',
                'ordering': ['-created_at'],
            },
        ),
    ]
