# Generated by Django 5.1.4 on 2026-01-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal')], default='daily', max_length=20, verbose_name='Frequência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('points_per_completion', models.PositiveIntegerField(default=10, help_text='Pontos ganhos ao completar todas as tarefas', verbose_name='Pontos por Conclusão')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, help_text='Tarefa obrigatória para conclusão do checklist', verbose_name='Obrigatório')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checklists.checklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['checklist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(max_length=20, verbose_name='Chave do Período')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Pontos Ganhos')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Concluído em')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='checklists.checklist', verbose_name='Checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Checklist Concluído',
                'verbose_name_plural': 'Checklists Concluídos',
                'unique_together': {('checklist', 'user', 'period_key')},
            },
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(help_text='Identificador único do período (YYYY-MM-DD, YYYY-Www, YYYY-MM)', max_length=20, verbose_name='Chave do Período')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Concluído em')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='checklists.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa Concluída',
                'verbose_name_plural': 'Tarefas Concluídas',
                'ordering': ['-completed_at'],
                'unique_together': {('task', 'user', 'period_key')},
            },
        ),
    ]
