# Generated by Django 5.1.4 on 2026-01-05 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklist_assigned_users'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_tasks', models.TextField(help_text='Lista de tarefas que estavam pendentes quando o checklist foi finalizado', verbose_name='Tarefas Pendentes')),
                ('period_key', models.CharField(help_text='Período em que o alerta foi criado', max_length=20, verbose_name='Chave do Período')),
                ('is_resolved', models.BooleanField(default=False, help_text='Marcado como resolvido pelo gestor', verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='checklists.checklist', verbose_name='Checklist')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company', verbose_name='Empresa')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta de Checklist',
                'verbose_name_plural': 'Alertas de Checklists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_resolved', '-created_at'], name='checklists__company_23ea88_idx')],
            },
        ),
    ]
