# Generated by Django 5.1.4 on 2026-01-05 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklistalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Primeiro remove unique_together antigo
        migrations.AlterUniqueTogether(
            name='checklistalert',
            unique_together=set(),
        ),
        # Adiciona campo task (nullable temporariamente)
        migrations.AddField(
            model_name='checklistalert',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Tarefa obrigatória que não foi concluída', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='checklists.task', verbose_name='Tarefa Pendente'),
        ),
        # Remove campo missing_tasks
        migrations.RemoveField(
            model_name='checklistalert',
            name='missing_tasks',
        ),
        # Remove alertas antigos que não têm task
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('checklists', 'ChecklistAlert').objects.filter(task__isnull=True).delete(),
            reverse_code=migrations.RunPython.noop
        ),
        # Torna task obrigatório
        migrations.AlterField(
            model_name='checklistalert',
            name='task',
            field=models.ForeignKey(help_text='Tarefa obrigatória que não foi concluída', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='checklists.task', verbose_name='Tarefa Pendente'),
        ),
        # Adiciona novo unique_together com task
        migrations.AlterUniqueTogether(
            name='checklistalert',
            unique_together={('checklist', 'task', 'user', 'period_key', 'is_resolved')},
        ),
    ]
