# Generated by Django 5.1.4 on 2026-01-06 12:14

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def remove_duplicate_alerts(apps, schema_editor):
    """
    Remove alertas duplicados, mantendo apenas o mais recente.
    Se houver um resolvido e um não resolvido, mantém o resolvido.
    """
    ChecklistAlert = apps.get_model('checklists', 'ChecklistAlert')
    
    # Agrupa por (checklist, task, user, period_key)
    from django.db.models import Max
    
    # Busca todas as combinações duplicadas
    duplicates = ChecklistAlert.objects.values(
        'checklist', 'task', 'user', 'period_key'
    ).annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        # Busca todos os alertas com essa combinação
        alerts = ChecklistAlert.objects.filter(
            checklist_id=dup['checklist'],
            task_id=dup['task'],
            user_id=dup['user'],
            period_key=dup['period_key']
        ).order_by('is_resolved', '-created_at')
        
        # Mantém o primeiro (resolvido se houver, caso contrário o mais recente)
        alert_to_keep = alerts.first()
        
        # Remove os demais
        alerts.exclude(id=alert_to_keep.id).delete()


def reverse_remove_duplicates(apps, schema_editor):
    # Não há como reverter a remoção de duplicados
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_change_alert_to_per_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Primeiro remove duplicados
        migrations.RunPython(remove_duplicate_alerts, reverse_remove_duplicates),
        # Depois altera a constraint
        migrations.AlterUniqueTogether(
            name='checklistalert',
            unique_together={('checklist', 'task', 'user', 'period_key')},
        ),
    ]
