# Generated by Django 5.1.4 on 2026-01-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#ff6a00', help_text='Cor em formato hexadecimal', max_length=7, verbose_name='Cor Primária')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Número máximo de colaboradores', verbose_name='Limite de Usuários')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('level', models.CharField(choices=[('admin_master', 'Admin Master'), ('gestor', 'Gestor'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20, verbose_name='Nível de Acesso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
