# Generated by Django 5.1.4 on 2026-01-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Data do último pagamento confirmado', null=True, verbose_name='Última Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_users_limit',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de colaboradores permitidos no plano', verbose_name='Limite Máximo de Usuários'),
        ),
        migrations.AddField(
            model_name='company',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Data prevista para a próxima cobrança', null=True, verbose_name='Próxima Data de Cobrança'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='bronze', help_text='Plano contratado (Bronze, Silver, Gold, Diamond)', max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('past_due', 'Pagamento Atrasado'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='trial', help_text='Status atual da assinatura da empresa', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateField(blank=True, help_text='Data de término do período de teste (se aplicável)', null=True, verbose_name='Fim do Período de Teste'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_users',
            field=models.PositiveIntegerField(default=50, help_text='[DEPRECATED] Use max_users_limit. Mantido para compatibilidade.', verbose_name='Limite de Usuários'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_status'], name='core_compan_subscri_8ff02a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['next_billing_date'], name='core_compan_next_bi_f0343d_idx'),
        ),
    ]
