# Generated by Django 5.1.4 on 2026-01-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.CharField(choices=[('great', '😊 Ótimo'), ('good', '🙂 Bom'), ('neutral', '😐 Neutro'), ('bad', '😕 Ruim'), ('sad', '😢 Triste')], default='neutral', max_length=20, verbose_name='Sentimento')),
                ('category', models.CharField(choices=[('suggestion', 'Sugestão'), ('complaint', 'Reclamação'), ('question', 'Dúvida'), ('praise', 'Elogio'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/attachments/', verbose_name='Anexo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='pending', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Se marcado, a identidade do autor não será revelada aos gestores', verbose_name='Anônimo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company', verbose_name='Empresa')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ticket de Feedback',
                'verbose_name_plural': 'Tickets de Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='Resposta da Equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentário de Feedback',
                'verbose_name_plural': 'Comentários de Feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
