# Generated by Django 5.1.4 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('in_dialogue', 'Em Diálogo'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
